import { FC } from "dreamland/core";

/**
 * Renders an `<img>` wrapped in a `<picture>` with a WebP `<source>` whenever
 * the `src` is a local `.jpg` / `.jpeg` path that has a sibling `.webp` file
 * generated by our build. Browsers without WebP support fall back to the
 * original JPEG via the `<img>` element.
 *
 * Used both for hand-rolled JSX (Homepage profile picture, ProjectCard
 * thumbnails, ProjectView hero) and as the MDX `img` component override in
 * BlogPost so every blog `![alt](path.jpg)` markdown image and `<img>` JSX
 * tag automatically gets a WebP source.
 *
 * Pass-through behaviour: any extra props on Pic are forwarded to the inner
 * `<img>` (alt, title, width, height, loading, class, etc.). Non-JPEG paths,
 * external URLs, and missing `src` values render a plain `<img>` unchanged.
 */
const LOCAL_JPEG_PATH = /^\/[^?#]*\.jpe?g(?:[?#]|$)/i;
const JPEG_EXT_IN_URL = /\.jpe?g(?=[?#]|$)/i;
// In a srcset list each candidate is followed by whitespace, comma, or end.
const JPEG_EXT_IN_SRCSET = /\.jpe?g(?=[\s,?#]|$)/gi;

function Pic(this: FC<Record<string, unknown>>) {
	const src = this.src as string | undefined;
	const srcset = (this.srcset as string | undefined) ?? undefined;

	// Build a clean passthrough for the inner <img>, excluding dreamland
	// internals (`cx`, `root`) and the MDX `components` map (which can leak
	// in through `this` when Pic is used as an MDX component override).
	const imgProps: Record<string, unknown> = {};
	for (const [key, value] of Object.entries(this)) {
		if (key === "cx" || key === "root" || key === "components") continue;
		imgProps[key] = value;
	}

	if (!src || typeof src !== "string" || !LOCAL_JPEG_PATH.test(src)) {
		return <img {...imgProps} />;
	}

	const webpSrc = src.replace(JPEG_EXT_IN_URL, ".webp");
	const webpSrcset = srcset ? srcset.replace(JPEG_EXT_IN_SRCSET, ".webp") : webpSrc;

	return (
		<picture>
			<source type="image/webp" srcset={webpSrcset} />
			<img {...imgProps} />
		</picture>
	);
}

export default Pic;
